
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(IsWindows)' == 'true' ">
    <TargetFrameworks>$(TargetFrameworks);net472</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>MassTransit</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MassTransit.CloudflareQueues</PackageId>
    <Title>MassTransit.CloudflareQueues</Title>
    <PackageTags>MassTransit;Cloudflare;Queues</PackageTags>
    <Description>MassTransit Cloudflare Queues transport support; $(Description)</Description>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\MassTransit.Abstractions\MassTransit.Abstractions.csproj" />
    <ProjectReference Include="..\..\MassTransit\MassTransit.csproj" />
  </ItemGroup>
</Project>
